/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Sistema;

/**
 *
 * @author Christian
 */
public class ModuloReporte extends javax.swing.JFrame {

    /**
     * Creates new form ModuloReporte
     */
    public ModuloReporte() {
        initComponents();
        jLabelFondo.setSize(500,490);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabeltITULO = new javax.swing.JLabel();
        jLabelAsunto = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jDateFechaIn = new com.toedter.calendar.JDateChooser();
        jLabelFechaIn = new javax.swing.JLabel();
        jLabelFechaFin = new javax.swing.JLabel();
        jDateFechaFin = new com.toedter.calendar.JDateChooser();
        jButtonGenerar = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabeltITULO.setBackground(new java.awt.Color(255, 255, 255));
        jLabeltITULO.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabeltITULO.setForeground(new java.awt.Color(255, 255, 255));
        jLabeltITULO.setText("REPORTE");
        getContentPane().add(jLabeltITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        jLabelAsunto.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelAsunto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAsunto.setText("ASUNTO:");
        getContentPane().add(jLabelAsunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 360, 50));
        getContentPane().add(jDateFechaIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 160, 30));

        jLabelFechaIn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelFechaIn.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFechaIn.setText("FECHA DE INICIO:");
        getContentPane().add(jLabelFechaIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabelFechaFin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelFechaFin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFechaFin.setText("FECHA DE FINALIZACION:");
        getContentPane().add(jLabelFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));
        getContentPane().add(jDateFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 160, 30));

        jButtonGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Sistema/new1.png"))); // NOI18N
        jButtonGenerar.setText("Generar Reporte");
        getContentPane().add(jButtonGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 460, -1, 50));

        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Sistema/pastilla.png"))); // NOI18N
        jButtonGuardar.setText("Guardar");
        getContentPane().add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 457, 140, 50));

        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Sistema/eliminarventa.png"))); // NOI18N
        jButtonEliminar.setText("Eliminar");
        getContentPane().add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 120, 50));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Sistema/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 0, 1090, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuloReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuloReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuloReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuloReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModuloReporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGenerar;
    private javax.swing.JButton jButtonGuardar;
    private com.toedter.calendar.JDateChooser jDateFechaFin;
    private com.toedter.calendar.JDateChooser jDateFechaIn;
    private javax.swing.JLabel jLabelAsunto;
    private javax.swing.JLabel jLabelFechaFin;
    private javax.swing.JLabel jLabelFechaIn;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabeltITULO;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
